version: "3.8"

services:
  compiler:
    container_name: compiler_ubuntu
    build:
      context: .
      dockerfile: DockerFile
    user: root
    ports:
      - "8000:8000"
    tty: true
    stdin_open: true
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./app:/app
