FROM ubuntu:latest

ARG DEBIAN_FRONTEND=interactive

WORKDIR /compile_server

COPY ./app ./app

RUN \
    apt update -y \
    && apt install software-properties-common -y \
    && apt upgrade -y \
    && apt install -y git python3-pip openjdk-8-jdk\
    && pip3 install -r app/requirements.txt \
    && echo -e "\nexport JAVA_HOME=$(dirname $(dirname $(readlink -f $(which java)))) \nexport PATH=$PATH:$JAVA_HOME/bin" >> ~/.profile \
    && . ~/.profile

# python@3.10이 이미 ubuntu@22.04에 내포되어 있음.